# Generated by Django 5.1.2 on 2024-10-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_ministudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinstitution',
            name='institute_lock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
