# Generated by Django 5.0.7 on 2024-11-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_ministudy', '0003_newinstitution_institute_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestions_improvements',
            fields=[
                ('si_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('si_user_name', models.CharField(max_length=55)),
                ('si_user', models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Parent', 'Parent')], max_length=15)),
                ('si_suggestion', models.TextField()),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'suggestions_improvements',
            },
        ),
    ]
