# Generated by Django 5.0.7 on 2024-11-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_ministudy', '0004_suggestions_improvements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('distributer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distributer_name', models.CharField(max_length=155)),
                ('distributer_number', models.CharField(max_length=15)),
                ('distributer_email', models.EmailField(max_length=254, unique=True)),
                ('distributer_password', models.CharField(default='12345678', max_length=155)),
                ('distributer_document', models.FileField(upload_to='uploads/')),
                ('distributer_address', models.TextField()),
            ],
            options={
                'db_table': 'Distributor',
            },
        ),
        migrations.CreateModel(
            name='Distributer_Institute',
            fields=[
                ('distributer_institute_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distributer_institute_date', models.DateField(auto_now_add=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('distributer_institute_distributer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_ministudy.distributor')),
            ],
            options={
                'db_table': 'Distributer_Institute',
            },
        ),
    ]
