# Generated by Django 5.0.7 on 2024-11-19 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_ministudy', '0005_distributor_distributer_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributer_Payment',
            fields=[
                ('distributer_payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distributer_payment', models.IntegerField()),
                ('distributer_payment_date', models.DateField(auto_now_add=True)),
                ('distributer_payment_distributer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_ministudy.distributor')),
            ],
            options={
                'db_table': 'Distributer_Payment',
            },
        ),
    ]
