# Generated by Django 5.0.7 on 2024-11-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_ministudy', '0007_newinstitution_institute_logo_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinstitution',
            name='institute_admin_app',
            field=models.FileField(blank=True, null=True, upload_to='institute_app/'),
        ),
        migrations.AddField(
            model_name='newinstitution',
            name='institute_admin_app_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newinstitution',
            name='institute_parent_app',
            field=models.FileField(blank=True, null=True, upload_to='institute_app/'),
        ),
        migrations.AddField(
            model_name='newinstitution',
            name='institute_parent_app_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newinstitution',
            name='institute_student_app',
            field=models.FileField(blank=True, null=True, upload_to='institute_app/'),
        ),
        migrations.AddField(
            model_name='newinstitution',
            name='institute_student_app_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newinstitution',
            name='institute_teacher_app',
            field=models.FileField(blank=True, null=True, upload_to='institute_app/'),
        ),
        migrations.AddField(
            model_name='newinstitution',
            name='institute_teacher_app_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
