# Generated by Django 5.0.7 on 2024-11-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_ministudy', '0008_newinstitution_institute_admin_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinstitution',
            name='institute_admin_app',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newinstitution',
            name='institute_parent_app',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newinstitution',
            name='institute_student_app',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newinstitution',
            name='institute_teacher_app',
            field=models.TextField(blank=True, null=True),
        ),
    ]
