# Generated by Django 5.0.6 on 2024-06-27 11:38

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_pass', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_otp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AdminData',
            },
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('brd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brd_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Boards',
            },
        ),
        migrations.CreateModel(
            name='Chepter',
            fields=[
                ('chep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chep_name', models.CharField(max_length=100)),
                ('chep_sem', models.CharField(blank=True, max_length=20)),
                ('chep_icon', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'chepter',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=500)),
                ('event_date', models.DateField()),
                ('event_img', models.ImageField(upload_to='uploads/events')),
                ('event_desc', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('fac_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fac_name', models.CharField(max_length=100)),
                ('fac_number', models.CharField(max_length=20)),
                ('fac_email', models.CharField(max_length=100)),
                ('fac_address', models.TextField()),
                ('Subjects', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Chepterwise_material',
            fields=[
                ('cm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cm_filename', models.CharField(max_length=100)),
                ('cm_file', models.FileField(upload_to='uploads/')),
                ('cm_file_icon', models.ImageField(blank=True, null=True, upload_to='file_icons/')),
                ('cm_chepter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.chepter')),
            ],
            options={
                'db_table': 'Chepterwise_Material',
            },
        ),
        migrations.CreateModel(
            name='Std',
            fields=[
                ('std_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=10)),
                ('std_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.boards')),
            ],
            options={
                'db_table': 'std',
            },
        ),
        migrations.CreateModel(
            name='Packs',
            fields=[
                ('pack_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pack_name', models.CharField(max_length=50)),
                ('pack_fees', models.CharField(max_length=20)),
                ('pack_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Chepterwise_test',
            fields=[
                ('test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('test_sem', models.CharField(choices=[('sem1', 'sem1'), ('sem2', 'sem2')], max_length=50)),
                ('test_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'chepterwise_test',
            },
        ),
        migrations.AddField(
            model_name='chepter',
            name='chep_std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std'),
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=50)),
                ('batch_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announce_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('announce_title', models.CharField(max_length=100)),
                ('announce_msg', models.TextField()),
                ('announce_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('announce_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.batches')),
                ('announce_std', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stud_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=200)),
                ('stud_lastname', models.CharField(max_length=200)),
                ('stud_contact', models.CharField(max_length=20)),
                ('stud_username', models.CharField(max_length=40)),
                ('stud_email', models.EmailField(max_length=100)),
                ('stud_dob', models.DateField()),
                ('stud_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('stud_guardian_name', models.CharField(max_length=200)),
                ('stud_guardian_email', models.EmailField(max_length=200)),
                ('stud_guardian_number', models.CharField(max_length=20)),
                ('stud_guardian_profession', models.CharField(max_length=50)),
                ('stud_address', models.TextField()),
                ('stud_pass', models.TextField(blank=True, null=True)),
                ('stud_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('stud_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.batches')),
                ('stud_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.packs')),
                ('stud_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50, unique=True)),
                ('sub_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.AddField(
            model_name='packs',
            name='pack_subjects',
            field=models.ManyToManyField(blank=True, to='adminside.subject'),
        ),
        migrations.AddField(
            model_name='chepter',
            name='chep_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.subject'),
        ),
        migrations.CreateModel(
            name='Test_questions_answer',
            fields=[
                ('tq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tq_q_type', models.CharField(choices=[('Question_Answer', 'Question_Answer'), ('MCQ', 'MCQ'), ('Filling_Blanks', 'Filling_Blanks'), ('True_False', 'True_False')], max_length=50)),
                ('tq_question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('tq_answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('tq_weightage', models.IntegerField()),
                ('tq_hint', models.TextField(blank=True, null=True)),
                ('tq_optiona', models.CharField(blank=True, max_length=200, null=True)),
                ('tq_optionb', models.CharField(blank=True, max_length=200, null=True)),
                ('tq_optionc', models.CharField(blank=True, max_length=200, null=True)),
                ('tq_optiond', models.CharField(blank=True, max_length=200, null=True)),
                ('tq_chepter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.chepter')),
                ('tq_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.chepterwise_test')),
            ],
            options={
                'db_table': 'test_questions_answer',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('tt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tt_day', models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=100)),
                ('tt_time1', models.TimeField()),
                ('tt_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.batches')),
                ('tt_subject1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.subject')),
                ('tt_tutor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.faculties')),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('atten_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('atten_date', models.DateTimeField(auto_now_add=True)),
                ('atten_present', models.BooleanField(default=0)),
                ('atten_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.students')),
                ('atten_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.timetable')),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
    ]
