# Generated by Django 5.0.7 on 2024-07-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt_section',
            fields=[
                ('doubt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doubt_doubt', models.TextField()),
                ('doubt_date', models.DateTimeField(auto_now_add=True)),
                ('doubt_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.students')),
                ('doubt_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.subject')),
            ],
            options={
                'db_table': 'Doubt_section',
            },
        ),
        migrations.CreateModel(
            name='Doubt_solution',
            fields=[
                ('solution_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('solution', models.TextField()),
                ('solution_verified', models.BooleanField(default=0)),
                ('solution_date', models.DateTimeField(auto_now_add=True)),
                ('solution_doubt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.doubt_section')),
                ('solution_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.students')),
                ('solution_verified_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.faculties')),
            ],
            options={
                'db_table': 'Doubt_solution',
            },
        ),
    ]
