# Generated by Django 5.0.6 on 2024-07-01 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chepterwise_test',
            name='test_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.subject'),
        ),
    ]
