# Generated by Django 5.0.6 on 2024-07-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_chepterwise_test_test_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='chepterwise_test',
            name='test_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
