# Generated by Django 5.0.7 on 2024-07-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_doubt_section_doubt_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='fac_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculties',
            name='fac_password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculties',
            name='fac_email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
        ),
    ]
