# Generated by Django 5.0.6 on 2024-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_alter_subject_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stud_pass',
            field=models.TextField(default='12345678'),
        ),
    ]
