# Generated by Django 5.0.6 on 2024-07-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_chepterwise_test_test_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_attempted_users',
            fields=[
                ('tau_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tau_completion_time', models.TimeField()),
                ('tau_attempted_questions', models.IntegerField()),
                ('tau_correct_ans', models.IntegerField()),
                ('tau_total_marks', models.FloatField()),
                ('tau_obtained_marks', models.FloatField()),
                ('tau_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.students')),
                ('tau_test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.chepterwise_test')),
            ],
            options={
                'db_table': 'test_attempted_users',
            },
        ),
        migrations.CreateModel(
            name='Test_submission',
            fields=[
                ('ts_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts_ans', models.TextField()),
                ('ts_attempted', models.BooleanField(default=0)),
                ('ts_que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.test_questions_answer')),
                ('ts_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.students')),
            ],
            options={
                'db_table': 'test_submission',
            },
        ),
    ]
