# Generated by Django 5.0.6 on 2024-07-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_faculties_fac_otp_faculties_fac_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stud_guardian_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='stud_guardian_password',
            field=models.CharField(blank=True, default='123456', max_length=100, null=True),
        ),
    ]
