# Generated by Django 5.0.7 on 2024-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_students_stud_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stud_profile',
            field=models.ImageField(blank=True, default='uploads/default_profile.jpg', null=True, upload_to='uploads/'),
        ),
    ]
