# Generated by Django 5.0.6 on 2024-07-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_test_attempted_users_test_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
