# Generated by Django 5.0.6 on 2024-08-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_students_stud_guardian_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Access',
            fields=[
                ('fa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fa_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.batches')),
                ('fa_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.faculties')),
                ('fa_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.subject')),
            ],
            options={
                'db_table': 'Faculty_Access',
            },
        ),
    ]
