# Generated by Django 5.0.7 on 2024-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_alter_students_stud_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='fac_password',
            field=models.CharField(blank=True, default='12345678', max_length=100, null=True),
        ),
    ]
