# Generated by Django 5.0.6 on 2024-07-04 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_alter_event_event_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_img',
        ),
        migrations.CreateModel(
            name='Event_Image',
            fields=[
                ('event_img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_img', models.ImageField(upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.event')),
            ],
            options={
                'db_table': 'event_imgs',
            },
        ),
    ]
