# Generated by Django 5.0.6 on 2024-08-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_faculty_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Collection',
            fields=[
                ('cehck_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('check_number', models.IntegerField()),
                ('check_paid', models.BooleanField(default=0)),
                ('check_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.students')),
            ],
            options={
                'db_table': 'Check_Collection',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discount_amount', models.IntegerField()),
                ('discount_pack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.packs')),
                ('discount_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.students')),
            ],
            options={
                'db_table': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='Fees_Collection',
            fields=[
                ('fees_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fees_paid', models.IntegerField()),
                ('fees_mode', models.CharField(choices=[('UPI', 'UPI'), ('CHECK', 'CHECK'), ('CASH', 'CASH'), ('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=255)),
                ('fees_date', models.DateTimeField(auto_now_add=True)),
                ('fees_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.students')),
            ],
            options={
                'db_table': 'Fees_Collection',
            },
        ),
    ]
