# Generated by Django 5.0.6 on 2024-08-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_check_collection_discount_fees_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check_Collection',
            new_name='Cheque_Collection',
        ),
        migrations.RenameField(
            model_name='cheque_collection',
            old_name='cehck_id',
            new_name='cheque_id',
        ),
        migrations.RenameField(
            model_name='cheque_collection',
            old_name='check_number',
            new_name='cheque_number',
        ),
        migrations.RenameField(
            model_name='cheque_collection',
            old_name='check_paid',
            new_name='cheque_paid',
        ),
        migrations.RenameField(
            model_name='cheque_collection',
            old_name='check_stud_id',
            new_name='cheque_stud_id',
        ),
        migrations.AlterModelTable(
            name='cheque_collection',
            table='cheque_Collection',
        ),
    ]
