# Generated by Django 5.0.6 on 2024-07-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_remove_event_event_img_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiries',
            fields=[
                ('inq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inq_name', models.CharField(max_length=200)),
                ('inq_lastname', models.CharField(max_length=200)),
                ('inq_contact', models.CharField(max_length=20)),
                ('inq_email', models.CharField(max_length=100)),
                ('inq_dob', models.DateField()),
                ('inq_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('inq_guardian_name', models.CharField(max_length=200)),
                ('inq_guardian_email', models.CharField(max_length=100)),
                ('inq_guardian_number', models.CharField(max_length=20)),
                ('inq_guardian_profession', models.CharField(max_length=50)),
                ('inq_address', models.TextField()),
                ('inq_subjects', models.CharField(max_length=100)),
                ('inq_schoolname', models.CharField(max_length=100)),
                ('inq_last_std_and_marks', models.CharField(max_length=20)),
                ('inq_howuknow', models.CharField(max_length=100)),
                ('inq_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'inquiries',
            },
        ),
    ]
