# Generated by Django 5.0.6 on 2024-08-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_alter_faculties_fac_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('syllabus_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('syllabus_status', models.BooleanField(default=0)),
                ('syllabus_date', models.DateTimeField(auto_now_add=True)),
                ('syllabus_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.chepter')),
            ],
            options={
                'db_table': 'Syllabus',
            },
        ),
    ]
