# Generated by Django 5.0.6 on 2024-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_status',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
