# Generated by Django 5.0.6 on 2024-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_rename_check_collection_cheque_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque_collection',
            name='cheque_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
