# Generated by Django 5.0.6 on 2024-08-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_alter_syllabus_syllabus_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Today_Teaching',
        ),
    ]
