# Generated by Django 5.0.6 on 2024-07-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_testing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testing',
        ),
    ]
