# Generated by Django 5.0.6 on 2024-07-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0009_delete_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_attempted_users',
            name='tau_correct_ans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test_attempted_users',
            name='tau_obtained_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
