# Generated by Django 5.0.6 on 2024-08-21 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_today_teaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='today_teaching',
            name='today_teaching_batches_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.batches'),
        ),
    ]
