# Generated by Django 5.0.6 on 2024-08-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_cheque_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque_collection',
            name='cheque_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='cheque_collection',
            table='Cheque_Collection',
        ),
    ]
