# Generated by Django 5.0.6 on 2024-08-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_alter_cheque_collection_cheque_expiry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cheque_Collection',
        ),
    ]
