# Generated by Django 5.0.7 on 2024-08-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_today_teaching_today_teaching_batches_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_collection',
            name='fees_date',
            field=models.DateTimeField(),
        ),
    ]
