# Generated by Django 5.0.7 on 2024-08-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0012_alter_fees_collection_fees_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_collection',
            name='fees_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
