# Generated by Django 5.0.7 on 2024-09-04 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0013_alter_fees_collection_fees_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_bank',
            fields=[
                ('qb_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qb_q_type', models.CharField(choices=[('Question_Answer', 'Question_Answer'), ('MCQ', 'MCQ'), ('Filling_Blanks', 'Filling_Blanks'), ('True_False', 'True_False')], max_length=50)),
                ('qb_question', models.TextField(blank=True, null=True)),
                ('qb_answer', models.TextField(blank=True, null=True)),
                ('qb_weightage', models.IntegerField()),
                ('qb_hint', models.TextField(blank=True, null=True)),
                ('qb_optiona', models.CharField(blank=True, max_length=200, null=True)),
                ('qb_optionb', models.CharField(blank=True, max_length=200, null=True)),
                ('qb_optionc', models.CharField(blank=True, max_length=200, null=True)),
                ('qb_optiond', models.CharField(blank=True, max_length=200, null=True)),
                ('qb_chepter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.chepter')),
            ],
            options={
                'db_table': 'question_bank',
            },
        ),
    ]
