# Generated by Django 5.0.6 on 2024-08-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0013_cheque_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packs',
            name='pack_fees',
            field=models.IntegerField(),
        ),
    ]
