# Generated by Django 5.0.6 on 2024-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0014_alter_packs_pack_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('bank_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=355)),
                ('bank_code', models.CharField(max_length=155)),
            ],
        ),
        migrations.AddField(
            model_name='cheque_collection',
            name='cheque_bank',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
