# Generated by Django 5.0.6 on 2024-08-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_banks_cheque_collection_cheque_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque_collection',
            name='cheque_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.banks'),
        ),
        migrations.AlterModelTable(
            name='banks',
            table='Banks',
        ),
    ]
