# Generated by Django 5.0.7 on 2024-09-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_remove_inquiries_inq_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stud_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='stud_guardian_profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
