# Generated by Django 5.0.6 on 2024-08-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0016_alter_cheque_collection_cheque_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stud_admission_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='stud_enrollment_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='stud_nationality',
            field=models.CharField(default='India', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='stud_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='students',
            name='stud_roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
