# Generated by Django 5.0.6 on 2024-08-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0017_students_stud_admission_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('credit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('credit_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'Credits',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
        migrations.AlterField(
            model_name='students',
            name='stud_profile',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
