# Generated by Django 5.1.1 on 2024-10-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0018_alter_students_stud_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_attempted_users',
            name='tau_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
