# Generated by Django 5.0.7 on 2024-10-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0020_students_stud_telegram_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='stud_telegram_chat_id',
            new_name='stud_telegram_parentschat_id',
        ),
        migrations.AddField(
            model_name='students',
            name='stud_telegram_studentchat_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
