# Generated by Django 5.0.7 on 2024-10-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0022_students_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='domain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boards',
            name='domain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
