# Generated by Django 5.1.1 on 2024-10-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0025_newinstitution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewInstitution',
        ),
    ]
