# Generated by Django 5.1.2 on 2024-10-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0027_remove_inquiries_stud_pack_inquiries_inq_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='domain_name',
            new_name='stud_domain_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='unique_code',
            new_name='stud_unique_code',
        ),
        migrations.AddField(
            model_name='students',
            name='stud_onesignal_player_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
