# Generated by Django 5.1.2 on 2024-10-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0029_rename_stud_domain_name_students_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='stud_unique_code',
            new_name='unique_code',
        ),
    ]
