# Generated by Django 5.1.2 on 2024-10-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0030_rename_stud_unique_code_students_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='admin_onesignal_player_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faculties',
            name='fac_onesignal_player_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='guardian_onesignal_player_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
