# Generated by Django 5.0.7 on 2024-10-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0031_admindata_admin_onesignal_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='admin_onesignal_player_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
