# Generated by Django 5.1.2 on 2024-10-21 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0032_alter_admindata_admin_onesignal_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt_section',
            name='doubt_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.faculties'),
        ),
        migrations.AlterField(
            model_name='students',
            name='stud_onesignal_player_id',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
