# Generated by Django 5.0.7 on 2024-10-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0033_doubt_section_doubt_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='brd_name',
            field=models.CharField(max_length=20),
        ),
    ]
