# Generated by Django 5.1.2 on 2024-10-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0033_doubt_section_doubt_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stud_lock',
            field=models.BooleanField(default=True),
        ),
    ]
