# Generated by Django 5.1.2 on 2024-10-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0034_students_stud_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stud_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='stud_lock',
            field=models.BooleanField(default=False),
        ),
    ]
