# Generated by Django 5.1.2 on 2024-10-22 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0035_students_stud_paid_alter_students_stud_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt_solution',
            name='solution_teacher_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doubt_solution',
            name='solution_stud_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.students'),
        ),
    ]
