# Generated by Django 5.1.2 on 2024-10-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0034_alter_boards_brd_name'),
        ('adminside', '0036_doubt_solution_solution_teacher_id_and_more'),
    ]

    operations = [
    ]
