# Generated by Django 5.1.2 on 2024-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0037_merge_20241024_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='inq_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
