# Generated by Django 5.0.7 on 2024-10-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0038_inquiries_inq_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='fac_profile',
            field=models.ImageField(blank=True, default='uploads/default_profile.jpg', null=True, upload_to='uploads/'),
        ),
    ]
