# Generated by Django 5.0.7 on 2024-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0039_faculties_fac_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_bank',
            name='domain_name',
        ),
        migrations.AddField(
            model_name='question_bank',
            name='qb_std',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='question_bank',
            name='qb_subject',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank',
            name='qb_chepter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
