# Generated by Django 5.0.7 on 2024-10-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0040_remove_question_bank_domain_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chepter',
            name='chep_icon',
        ),
        migrations.AlterField(
            model_name='chepterwise_test',
            name='test_sem',
            field=models.CharField(blank=True, choices=[('sem1', 'sem1'), ('sem2', 'sem2')], max_length=50, null=True),
        ),
    ]
