# Generated by Django 5.0.7 on 2024-10-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0040_remove_question_bank_domain_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_templates',
            fields=[
                ('mail_temp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mail_temp_html', models.TextField(blank=True, null=True)),
                ('mail_temp_type', models.CharField(choices=[('Itroduction_mail', 'Itroduction_mail'), ('Marketing_mail', 'Marketing_mail')], max_length=50)),
                ('mail_temp_selected', models.BooleanField(default=0)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mail_templates',
            },
        ),
    ]
