# Generated by Django 5.0.7 on 2024-10-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0041_mail_templates'),
        ('adminside', '0041_remove_chepter_chep_icon_and_more'),
    ]

    operations = [
    ]
