# Generated by Django 5.0.7 on 2024-10-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0042_merge_20241028_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_templates',
            name='mail_temp_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='mail_variables',
            fields=[
                ('mail_variables_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mail_variables_name', models.CharField(max_length=100)),
                ('mail_variables_mail_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.mail_templates')),
            ],
            options={
                'db_table': 'mail_variables',
            },
        ),
    ]
