# Generated by Django 5.0.7 on 2024-10-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0043_mail_templates_mail_temp_name_mail_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_variables',
            name='mail_variables_mail_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_template', to='adminside.mail_templates'),
        ),
    ]
