# Generated by Django 5.0.7 on 2024-10-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0045_alter_mail_templates_mail_temp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='fac_syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.faculties'),
        ),
    ]
