# Generated by Django 5.0.7 on 2024-10-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0046_syllabus_fac_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='Completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
