# Generated by Django 5.0.7 on 2024-11-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0042_merge_20241028_1731'),
        ('adminside', '0047_syllabus_completion_time'),
    ]

    operations = [
    ]
