# Generated by Django 5.0.7 on 2024-11-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0048_merge_20241105_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestions_improvements',
            fields=[
                ('si_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('si_user_name', models.CharField(max_length=55)),
                ('si_user', models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Parent', 'Parent')], max_length=15)),
                ('si_suggestion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='mail_templates',
            name='mail_temp_type',
            field=models.CharField(choices=[('Itroduction_mail', 'Itroduction_mail'), ('Marketing_mail', 'Marketing_mail'), ('Announcement_mail', 'Announcement_mail'), ('Attendance_mail', 'Attendance_mail'), ('Cheque_mail', 'Cheque_mail'), ('Cheque_update_mail', 'Cheque_update_mail'), ('Faculty_mail', 'Faculty_mail'), ('Institute_mail', 'Institute_mail'), ('Parent_meeting_mail', 'Parent_meeting_mail'), ('Payment_mail', 'Payment_mail'), ('Student_mail', 'Student_mail'), ('Timetable_mail', 'Timetable_mail')], max_length=50),
        ),
    ]
