# Generated by Django 5.0.7 on 2024-11-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0050_suggestions_improvements_domain_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='suggestions_improvements',
        ),
    ]
