# Generated by Django 5.0.7 on 2024-11-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0049_students_stude_created_at_and_more'),
        ('adminside', '0052_syllabus_syllabus_batch'),
    ]

    operations = [
    ]
