# Generated by Django 5.0.7 on 2024-11-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0053_merge_20241106_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='admin_pass',
            field=models.CharField(blank=True, default='123456', max_length=100, null=True),
        ),
    ]
