# Generated by Django 5.0.7 on 2024-11-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0061_alter_mail_variables_mail_variables_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_templates',
            name='mail_temp_type',
            field=models.CharField(choices=[('Introduction_mail', 'Introduction_mail'), ('Marketing_mail', 'Marketing_mail'), ('Announcement_mail', 'Announcement_mail'), ('Attendance_mail', 'Attendance_mail'), ('Cheque_mail', 'Cheque_mail'), ('Cheque_update_mail', 'Cheque_update_mail'), ('Faculty_mail', 'Faculty_mail'), ('Institute_mail', 'Institute_mail'), ('Parent_meeting_mail', 'Parent_meeting_mail'), ('Payment_mail', 'Payment_mail'), ('Student_mail', 'Student_mail'), ('Timetable_mail', 'Timetable_mail'), ('Admin_mail', 'Admin_mail'), ('Student_marks_mail', 'Student_marks_mail')], max_length=50),
        ),
    ]
