# Generated by Django 5.0.7 on 2024-11-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0062_alter_mail_templates_mail_temp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complaint_subject', models.CharField(max_length=255)),
                ('complaint_message', models.TextField()),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_handle', models.BooleanField(default=0)),
                ('domain_name', models.CharField(max_length=100)),
                ('complaint_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.students')),
            ],
            options={
                'db_table': 'Complaint',
            },
        ),
    ]
