# Generated by Django 5.0.7 on 2024-11-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0063_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbox',
            fields=[
                ('chatbox_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chatbox_sender', models.CharField(max_length=100)),
                ('chatbox_receiver', models.CharField(max_length=100)),
                ('chatbox_chat', models.TextField()),
                ('domain_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Chatbox',
            },
        ),
    ]
