# Generated by Django 5.0.7 on 2024-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0064_chatbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='domain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
