# Generated by Django 5.0.7 on 2024-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0064_chatbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='chatbox_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
