# Generated by Django 5.0.7 on 2024-11-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0065_alter_complaint_domain_name'),
        ('adminside', '0065_chatbox_chatbox_datetime'),
    ]

    operations = [
    ]
