# Generated by Django 5.0.7 on 2024-11-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0067_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_user',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
