# Generated by Django 5.0.7 on 2024-11-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0068_notification_notify_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expense_amount', models.FloatField()),
                ('expense_name', models.CharField(max_length=255)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('expense_desc', models.TextField(blank=True, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Expense',
            },
        ),
    ]
