# Generated by Django 5.0.7 on 2024-11-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0069_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('Salary', 'Salary'), ('Equipments', 'Equipments'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
