# Generated by Django 5.0.7 on 2024-11-13 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0070_expense_expense_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=155)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(blank=True, max_length=155, null=True)),
                ('material_file', models.FileField(upload_to='uploads/')),
                ('material_icon', models.ImageField(blank=True, null=True, upload_to='file_icons/')),
                ('material_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.groups')),
            ],
            options={
                'db_table': 'Materials',
            },
        ),
    ]
