# Generated by Django 5.0.7 on 2024-11-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0071_groups_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='domain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
