# Generated by Django 5.0.7 on 2024-11-14 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0072_materials_domain_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials_access',
            fields=[
                ('material_access_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('materialaccess_email', models.CharField(max_length=100)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('materialaccess_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.groups')),
            ],
            options={
                'db_table': 'Material_access',
            },
        ),
    ]
