# Generated by Django 5.0.7 on 2024-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0074_alter_admindata_admin_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chepter',
            name='chep_name',
            field=models.CharField(max_length=400),
        ),
    ]
