# Generated by Django 5.0.7 on 2024-11-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0075_alter_chepter_chep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chepter',
            name='chep_name',
            field=models.TextField(),
        ),
    ]
