# Generated by Django 5.0.7 on 2024-11-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0076_alter_chepter_chep_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmimLead',
            fields=[
                ('adminlead_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adminlead_name', models.CharField(max_length=155)),
                ('adminlead_email', models.EmailField(max_length=254, unique=True)),
                ('adminlead_contact', models.IntegerField()),
                ('adminlead_standard', models.CharField(max_length=50)),
                ('adminlead_subject', models.CharField(max_length=155)),
                ('adminlead_last_talkdate', models.DateField()),
                ('adminlead_future_talkdate', models.DateField()),
                ('adminlead_level', models.CharField(choices=[('Warm', 'Warm'), ('Medium', 'Medium'), ('Cold', 'Cold')], max_length=100)),
                ('adminlead_conversiondetails', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'AdmimLead',
            },
        ),
    ]
