# Generated by Django 5.0.7 on 2024-11-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0078_admimlead_domain_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdmimLead',
            new_name='AdminLead',
        ),
        migrations.AlterModelTable(
            name='adminlead',
            table='AdminLead',
        ),
    ]
