# Generated by Django 5.0.7 on 2024-11-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0079_rename_admimlead_adminlead_alter_adminlead_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlead',
            name='adminlead_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminlead',
            name='adminlead_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
