# Generated by Django 5.0.7 on 2024-11-22 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0080_alter_adminlead_adminlead_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice_test',
            fields=[
                ('practice_test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('practice_test_name', models.CharField(max_length=100)),
                ('practice_test_chapter_name', models.CharField(max_length=300)),
                ('Practice_test_std', models.CharField(max_length=100)),
                ('Practice_test_subject', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Practice_test',
            },
        ),
        migrations.CreateModel(
            name='Practice_test_questions',
            fields=[
                ('practice_test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('practice_test_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Filling_Blanks', 'Filling_Blanks'), ('True_False', 'True_False')], max_length=50)),
                ('practice_test_question', models.TextField()),
                ('practice_test_answer', models.TextField()),
                ('practice_test_weightage', models.IntegerField()),
                ('practice_test_option_a', models.CharField(blank=True, max_length=155, null=True)),
                ('practice_test_option_b', models.CharField(blank=True, max_length=155, null=True)),
                ('practice_test_option_c', models.CharField(blank=True, max_length=155, null=True)),
                ('practice_test_option_d', models.CharField(blank=True, max_length=155, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('practice_test_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.practice_test')),
            ],
            options={
                'db_table': 'Practice_test_questions',
            },
        ),
    ]
