# Generated by Django 5.0.7 on 2024-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0081_practice_test_practice_test_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_test_questions',
            name='practice_test_attempted',
            field=models.CharField(choices=[('Attemped', 'Attemped'), ('Not_attemped', 'Not_attemped'), ('Answered', 'Answered'), ('Not_answered', 'Not_answered')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
