# Generated by Django 5.0.7 on 2024-11-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0082_practice_test_questions_practice_test_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_image',
            name='event_img',
            field=models.ImageField(upload_to='uploads/events/'),
        ),
    ]
