# Generated by Django 5.0.7 on 2024-11-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0083_alter_event_image_event_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_videos',
            fields=[
                ('sv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sv_name', models.CharField(blank=True, max_length=155, null=True)),
                ('sv_video_file', models.FileField(upload_to='uploads/videos/')),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('material_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.groups')),
            ],
            options={
                'db_table': 'Study_videos',
            },
        ),
    ]
