# Generated by Django 5.0.7 on 2024-11-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0085_remove_practice_test_questions_practice_test_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlead',
            name='adminlead_contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
