# Generated by Django 5.0.7 on 2024-11-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0086_alter_adminlead_adminlead_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetestattempted',
            name='domain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
