# Generated by Django 5.0.7 on 2024-11-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0087_practicetestattempted_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='atten_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
