# Generated by Django 5.0.7 on 2024-11-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0088_alter_attendance_atten_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='atten_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
