# Generated by Django 5.0.7 on 2024-11-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0089_alter_attendance_atten_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Review',
            fields=[
                ('teacher_review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teacher_review', models.IntegerField()),
                ('review_date', models.DateField(auto_now_add=True)),
                ('teacher_review_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.students')),
                ('teacher_review_teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.faculties')),
            ],
            options={
                'db_table': 'Teacher_Review',
                'unique_together': {('teacher_review_teacher_id', 'teacher_review_student_id')},
            },
        ),
    ]
