# Generated by Django 5.0.7 on 2024-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0089_alter_attendance_atten_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_bank',
            name='detailed_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
