# Generated by Django 5.0.7 on 2024-11-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0090_question_bank_detailed_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_test_questions',
            name='detailed_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
