# Generated by Django 5.0.7 on 2024-11-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0091_practice_test_questions_detailed_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice_test_questions',
            old_name='practice_test_id',
            new_name='practice_test_question_id',
        ),
    ]
