# Generated by Django 5.0.7 on 2024-11-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0092_alter_teacher_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_review',
            name='teacher_review_subject',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
