# Generated by Django 5.0.7 on 2024-11-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0093_teacher_review_teacher_review_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_review',
            name='teacher_review_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.subject'),
        ),
    ]
