# Generated by Django 5.0.6 on 2024-05-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('brd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brd_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Boards',
            },
        ),
        migrations.CreateModel(
            name='Std',
            fields=[
                ('std_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=10)),
                ('std_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.boards')),
            ],
            options={
                'db_table': 'std',
            },
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=50)),
                ('batch_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50, unique=True)),
                ('sub_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Packs',
            fields=[
                ('pack_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pack_name', models.CharField(max_length=50)),
                ('pack_fees', models.CharField(max_length=20)),
                ('pack_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
                ('pack_subjects', models.ManyToManyField(blank=True, to='adminside.subject')),
            ],
            options={
                'db_table': 'packages',
            },
        ),
    ]
