# Generated by Django 5.0.6 on 2024-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_admindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='admin_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
