# Generated by Django 5.0.6 on 2024-06-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_admindata_admin_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='brd_file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
