# Generated by Django 5.0.6 on 2024-06-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_remove_boards_brd_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announce_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('announce_title', models.CharField(max_length=100)),
                ('announce_msg', models.TextField(max_length=100)),
                ('announce_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.batches')),
                ('announce_std', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
    ]
