# Generated by Django 5.0.6 on 2024-06-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stud_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=200)),
                ('stud_lastname', models.CharField(max_length=200)),
                ('stud_contact', models.CharField(max_length=20)),
                ('stud_username', models.CharField(max_length=40)),
                ('stud_email', models.EmailField(max_length=100)),
                ('stud_dob', models.DateField()),
                ('stud_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('stud_guardian_name', models.CharField(max_length=200)),
                ('stud_guardian_email', models.EmailField(max_length=200)),
                ('stud_guardian_number', models.CharField(max_length=20)),
                ('stud_guardian_profession', models.CharField(max_length=50)),
                ('stud_address', models.TextField()),
                ('stud_pass', models.TextField(blank=True, null=True)),
                ('stud_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('stud_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.batches')),
                ('stud_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.packs')),
                ('stud_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
