# Generated by Django 4.1.3 on 2024-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='announce_msg',
            field=models.TextField(),
        ),
    ]
