# Generated by Django 4.1.3 on 2024-06-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_alter_announcements_announce_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='announce_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
