# Generated by Django 5.0.6 on 2024-06-21 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_alter_subject_sub_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chepter',
            fields=[
                ('chep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chep_name', models.CharField(max_length=100)),
                ('chep_sem', models.CharField(blank=True, max_length=20)),
                ('chep_icon', models.ImageField(upload_to='uploads/')),
                ('chep_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.std')),
                ('chep_sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.subject')),
            ],
            options={
                'db_table': 'chepter',
            },
        ),
    ]
