# Generated by Django 5.0.6 on 2024-06-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_chepter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chepterwise_material',
            fields=[
                ('cm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cm_filename', models.CharField(max_length=100)),
                ('cm_file', models.FileField(upload_to='uploads/')),
                ('cm_file_icon', models.ImageField(blank=True, null=True, upload_to='file_icons/')),
                ('cm_chepter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.chepter')),
            ],
            options={
                'db_table': 'Chepterwise_Material',
            },
        ),
    ]
